version: '3.9'

services:
  db:
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: |
      bash -c "rm -f tmp/pids/server.pid && \
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/comarev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
