name: Rubocop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ruby_lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - name: linter
      run: bundle exec rubocop
